### ISSUE TITLE
Spotify is opened as normal without any change

### ISSUE THREAD

**Issue by frogg** [devinhalladay/spotio#4] opened 2016-08-22 18:54 UTC
I downloaded the app (blue app icon in downloads folder).
The app icon in the dock changes to the normal green once the app is started and also the user interface is exactly the same as before (black, not white).

**Comment by devinhalladay** [comment] 2016-08-22 18:57
Hey! Make sure you quit your existing spotify app with cmd + q first, otherwise what you're describing will happen :)

**Comment by devinhalladay** [comment] 2016-08-22 18:58
Try that and please let me know if it works so I can close this!

**Comment by frogg** [comment] 2016-08-22 18:58
Hi Devin - thanks for your answer, that's what I did, but it still happened. Could this be related to the "Spotify Helper" app in autostart?

**Comment by devinhalladay** [comment] 2016-08-22 18:59
Hmm, possibly. Can you try quitting that via Activity Monitor and then launch Spotio?

**Comment by frogg** [comment] 2016-08-22 19:02
I found this one in activity monitor, but it's still not working after I quit all objects which have "Spotify" in their name.

![bildschirmfoto 2016-08-22 um 21 00 01](https://cloud.githubusercontent.com/assets/5204169/17867629/93954680-68ab-11e6-8311-74ce17c8759e.png)

**Comment by devinhalladay** [comment] 2016-08-22 19:02
Strange...what version of OS X are you running?

**Comment by frogg** [comment] 2016-08-22 19:03
El Capitan 10.11.6 (I think it's the newest non-beta).

**Comment by devinhalladay** [comment] 2016-08-22 19:08
Can you run `ps -ax` in your terminal for me and post the output here please? I'm not sure why it's not working but I have a feeling there's some kind of sneaky process still running that's preventing it from working.

**Comment by devinhalladay** [comment] 2016-08-22 19:08
Typically if the app launches and reverts to the old theme and icon it means another version of the OG Spotify.app is running somewhere

**Comment by frogg** [comment] 2016-08-22 19:11
Here you go:
```
  PID TTY           TIME CMD
    1 ??         0:25.01 /sbin/launchd
   42 ??         0:07.86 /usr/sbin/syslogd
   43 ??         0:02.37 /usr/libexec/UserEventAgent (System)
   45 ??         0:00.90 /usr/libexec/kextd
   46 ??         0:03.76 /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/Support/fseventsd
   50 ??         0:00.19 /System/Library/CoreServices/appleeventsd --server
   51 ??         0:00.75 /usr/libexec/configd
   52 ??         0:00.71 /System/Library/CoreServices/powerd.bundle/powerd
   58 ??         0:00.28 /usr/libexec/airportd
   59 ??         0:00.24 /usr/libexec/warmd
   61 ??         1:18.76 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Support/mds
   65 ??         0:00.03 /System/Library/CoreServices/iconservicesd
   66 ??         0:00.01 /System/Library/CoreServices/iconservicesagent
   67 ??         0:00.59 /usr/libexec/diskarbitrationd
   69 ??         0:03.50 /usr/libexec/coreduetd
   70 ??         0:00.02 /usr/libexec/wdhelper
   72 ??         0:03.35 /usr/libexec/opendirectoryd
   73 ??         0:00.02 /usr/sbin/wirelessproxd
   75 ??         0:02.50 /System/Library/PrivateFrameworks/ApplePushService.framework/apsd
   76 ??         0:04.32 /System/Library/CoreServices/launchservicesd
   77 ??         0:00.07 /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/Resources/usbmuxd -launchd
   78 ??         0:07.83 /usr/sbin/securityd -i
   79 ??         0:00.01 /usr/libexec/ptmd
   80 ??         0:00.43 /usr/libexec/locationd
   83 ??         0:00.53 /usr/sbin/blued
   84 ??         0:00.01 autofsd
   87 ??         0:00.07 /System/Library/PrivateFrameworks/Heimdal.framework/Helpers/kdc
   89 ??         0:01.82 /usr/sbin/mDNSResponder
   91 ??         0:00.42 /System/Library/PrivateFrameworks/GenerationalStorage.framework/Versions/A/Support/revisiond
   92 ??         0:00.01 /usr/sbin/KernelEventAgent
   93 ??         0:03.93 /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow console
   94 ??         0:00.02 /System/Library/CoreServices/logind
   96 ??         0:16.27 /usr/libexec/hidd
   97 ??         0:00.11 /usr/libexec/AirPlayXPCHelper
   98 ??         0:02.19 /usr/sbin/notifyd
  102 ??         0:00.46 /usr/sbin/distnoted daemon
  122 ??         0:00.10 aslmanager
  123 ??         0:00.16 /usr/libexec/diagnosticd
  125 ??         0:00.31 /usr/libexec/sandboxd
  127 ??         0:02.27 /usr/sbin/cfprefsd daemon
  128 ??         0:00.29 /System/Library/Frameworks/Security.framework/Versions/A/XPCServices/authd.xpc/Contents/MacOS/authd
  142 ??         0:00.87 /System/Library/CoreServices/coreservicesd
  144 ??         0:00.01 /System/Library/Frameworks/PCSC.framework/Versions/A/XPCServices/com.apple.ctkpcscd.xpc/Contents/MacOS/com.apple.ctkpcscd
  160 ??         0:00.01 /System/Library/Frameworks/CryptoTokenKit.framework/ctkd -s
  163 ??         0:00.04 /usr/libexec/secinitd
  165 ??         8:27.36 /System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreGraphics.framework/Resources/WindowServer -daemon
  174 ??         0:00.09 /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Support/awdd
  183 ??         1:36.87 /usr/sbin/coreaudiod
  188 ??         0:02.07 /usr/libexec/networkd
  189 ??         0:00.04 /System/Library/Frameworks/CoreAudio.framework/Versions/A/XPCServices/com.apple.audio.DriverHelper.xpc/Contents/MacOS/com.apple.audio.DriverHelper
  192 ??         0:00.13 /System/Library/Frameworks/Security.framework/Versions/A/XPCServices/com.apple.CodeSigningHelper.xpc/Contents/MacOS/com.apple.CodeSigningHelper
  193 ??         0:00.02 /usr/libexec/networkd_privileged
  194 ??         0:00.23 /usr/libexec/findmydeviced
  197 ??         0:00.04 /System/Library/PrivateFrameworks/CoreSymbolication.framework/coresymbolicationd
  198 ??         0:01.37 /usr/libexec/lsd runAsRoot
  203 ??         0:00.01 /usr/libexec/smd
  206 ??         0:33.84 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mds_stores
  207 ??         0:00.04 /System/Library/CoreServices/backupd.bundle/Contents/Resources/backupd-helper -launchd
  211 ??         0:00.02 /usr/libexec/nsurlsessiond --privileged
  212 ??         0:00.50 /usr/sbin/ntpd -c /private/etc/ntp-restrict.conf -n -g -p /var/run/ntpd.pid -f /var/db/ntp.drift
  213 ??         0:00.46 /usr/libexec/nehelper
  217 ??         0:00.08 /usr/libexec/usbd
  218 ??         0:00.01 /System/Library/CryptoTokenKit/com.apple.ifdreader.slotd/Contents/MacOS/com.apple.ifdreader
  219 ??         0:00.01 /usr/libexec/dpd
  220 ??         0:00.06 /System/Library/Frameworks/CoreMediaIO.framework/Resources/VDC.plugin/Contents/Resources/VDCAssistant
  221 ??         0:00.11 /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/Support/akd
  224 ??         0:00.15 /System/Library/PrivateFrameworks/CacheDelete.framework/deleted
  225 ??         0:00.01 /usr/libexec/periodic-wrapper daily
  226 ??         0:05.32 /usr/libexec/syspolicyd
  227 ??         0:16.98 /System/Library/CoreServices/Software Update.app/Contents/Resources/softwareupdated
  230 ??         0:00.03 /System/Library/PrivateFrameworks/SoftwareUpdate.framework/Resources/suhelperd
  302 ??         0:00.05 /System/Library/PrivateFrameworks/AmbientDisplay.framework/Versions/A/XPCServices/com.apple.AmbientDisplayAgent.xpc/Contents/MacOS/com.apple.AmbientDisplayAgent
  303 ??         0:00.13 /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/CVMServer
  332 ??         0:00.11 /System/Library/CoreServices/sharedfilelistd --enable-legacy-services
  333 ??         0:00.31 /usr/sbin/systemsoundserverd
  335 ??         0:00.02 /System/Library/PrivateFrameworks/AccountPolicy.framework/XPCServices/com.apple.AccountPolicyHelper.xpc/Contents/MacOS/com.apple.AccountPolicyHelper
  336 ??         0:00.05 /System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Resources/storeaccountd daemon
  339 ??         0:00.05 /System/Library/PrivateFrameworks/TCC.framework/Resources/tccd system
  340 ??         0:02.53 /usr/libexec/symptomsd
  346 ??         0:00.32 /usr/libexec/watchdogd
  349 ??         0:00.14 /usr/sbin/netbiosd
  350 ??         0:00.03 /usr/libexec/nsurlstoraged
  368 ??         0:02.63 /usr/sbin/cfprefsd agent
  369 ??         0:00.01 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdflagwriter
  370 ??         0:02.86 /usr/sbin/distnoted agent
  371 ??         0:01.96 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker-sizing -c MDSSizingWorker -m com.apple.mdworker.sizing
  381 ??         0:02.09 /System/Library/PrivateFrameworks/TCC.framework/Resources/tccd
  390 ??         0:00.35 /usr/libexec/systemstatsd
  391 ??         0:03.21 sysmond
  393 ??         0:00.01 /System/Library/Frameworks/AudioToolbox.framework/XPCServices/com.apple.audio.SandboxHelper.xpc/Contents/MacOS/com.apple.audio.SandboxHelper
  397 ??         0:00.04 /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/XPCServices/com.apple.PerformanceAnalysis.animationperfd.xpc/Contents/MacOS/com.apple.PerformanceAnalysis.animationperfd
  400 ??         0:16.61 /usr/libexec/securityd_service
  401 ??         0:00.91 /usr/libexec/UserEventAgent (Aqua)
  403 ??         0:00.50 /usr/sbin/universalaccessd launchd -s
  404 ??         0:00.73 /usr/libexec/lsd
  405 ??         0:01.01 /usr/sbin/usernoted
  406 ??         0:07.47 /System/Library/PrivateFrameworks/CalendarAgent.framework/Executables/CalendarAgent
  407 ??         0:57.16 /usr/libexec/nsurlsessiond
  408 ??         0:01.35 /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/Support/akd
  411 ??         0:13.83 /System/Library/PrivateFrameworks/CloudDocsDaemon.framework/Versions/A/Support/bird
  412 ??         0:00.39 /usr/libexec/secinitd
  413 ??         0:02.57 /System/Library/PrivateFrameworks/CalendarAgent.framework/Versions/A/XPCServices/CalNCService.xpc/Contents/MacOS/CalNCService
  414 ??         0:00.01 /usr/sbin/pboard
  415 ??         0:00.41 /System/Library/CoreServices/sharedfilelistd
  417 ??         0:00.32 /System/Library/PrivateFrameworks/Noticeboard.framework/Versions/A/Resources/nbagent.app/Contents/MacOS/nbagent
  418 ??         0:00.01 /System/Library/CoreServices/AirPort Base Station Agent.app/Contents/MacOS/AirPort Base Station Agent --launchd
  419 ??         0:09.63 /usr/libexec/nsurlstoraged
  420 ??         0:15.44 /System/Library/Frameworks/Accounts.framework/Versions/A/Support/accountsd
  421 ??         0:01.30 /System/Library/Frameworks/AddressBook.framework/Versions/A/XPCServices/com.apple.AddressBook.ContactsAccountsService.xpc/Contents/MacOS/com.apple.AddressBook.ContactsAccountsService
  423 ??         0:01.78 /System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd
  424 ??         0:03.09 /usr/libexec/secd
  425 ??         0:00.89 /System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Resources/storeaccountd
  427 ??         0:03.17 /System/Library/PrivateFrameworks/TelephonyUtilities.framework/callservicesd
  430 ??         0:00.20 /System/Library/PrivateFrameworks/IMFoundation.framework/XPCServices/IMRemoteURLConnectionAgent.xpc/Contents/MacOS/IMRemoteURLConnectionAgent
  431 ??         0:04.90 /System/Library/PrivateFrameworks/CoreSuggestions.framework/Versions/A/Support/suggestd
  432 ??         0:01.11 /System/Library/PrivateFrameworks/IMCore.framework/imagent.app/Contents/MacOS/imagent
  433 ??         0:01.37 /System/Library/PrivateFrameworks/IMDPersistence.framework/XPCServices/IMDPersistenceAgent.xpc/Contents/MacOS/IMDPersistenceAgent
  435 ??         0:00.19 /System/Library/CoreServices/mapspushd
  436 ??         0:00.26 /usr/libexec/fmfd
  437 ??         0:00.11 /System/Library/PrivateFrameworks/IMFoundation.framework/XPCServices/IMRemoteURLConnectionAgent.xpc/Contents/MacOS/IMRemoteURLConnectionAgent
  438 ??         0:00.55 /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/XPCServices/com.apple.geod.xpc/Contents/MacOS/com.apple.geod
  439 ??         0:00.28 /usr/sbin/filecoordinationd
  440 ??         0:33.69 /System/Library/PrivateFrameworks/CloudKitDaemon.framework/Support/cloudd
  441 ??         0:00.01 /System/Library/CoreServices/CrashReporterSupportHelper server-init
  442 ??         0:00.02 /System/Library/PrivateFrameworks/Noticeboard.framework/Versions/A/Resources/nbstated
  443 ??         0:00.06 /System/Library/PrivateFrameworks/CommunicationsFilter.framework/CMFSyncAgent.app/Contents/MacOS/CMFSyncAgent
  449 ??         0:00.88 /usr/libexec/amfid
  454 ??         0:00.06 /usr/libexec/taskgated -s
  459 ??         0:13.73 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal -psn_0_94231
  463 ??         0:03.88 /System/Library/CoreServices/Dock.app/Contents/MacOS/Dock
  464 ??         0:01.32 /System/Library/CoreServices/SystemUIServer.app/Contents/MacOS/SystemUIServer
  465 ??         0:04.47 /System/Library/CoreServices/Finder.app/Contents/MacOS/Finder
  470 ??         0:00.90 /System/Library/CoreServices/Spotlight.app/Contents/MacOS/Spotlight
  475 ??         0:00.26 /usr/libexec/sharingd
  476 ??         0:02.47 /usr/libexec/pkd
  477 ??         0:01.97 /System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Resources/storeassetd
  478 ??         0:00.03 /System/Library/PrivateFrameworks/CoreWLANKit.framework/Versions/A/XPCServices/WiFiProxy.xpc/Contents/MacOS/WiFiProxy
  479 ??         0:00.13 /System/Library/Frameworks/Security.framework/Versions/A/Resources/CloudKeychainProxy.bundle/Contents/MacOS/CloudKeychainProxy
  480 ??         0:00.35 /System/Library/CoreServices/iconservicesagent
  485 ??         0:00.20 /System/Library/CoreServices/Dock.app/Contents/XPCServices/com.apple.dock.extra.xpc/Contents/MacOS/com.apple.dock.extra
  488 ??         0:04.47 /System/Library/PrivateFrameworks/MessagesKit.framework/Resources/soagent.app/Contents/MacOS/soagent
  489 ??         0:00.04 /System/Library/PrivateFrameworks/CallHistory.framework/Support/CallHistoryPluginHelper
  490 ??         0:00.04 /System/Library/CoreServices/backupd.bundle/Contents/Resources/TMCacheDelete
  491 ??         0:05.89 /System/Library/PrivateFrameworks/PackageKit.framework/Resources/installd
  493 ??         0:00.99 /System/Library/PrivateFrameworks/ParsecUI.framework/Versions/A/Support/SpotlightNetHelper.app/Contents/MacOS/SpotlightNetHelper
  495 ??         0:00.71 /System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/XPCServices/com.apple.CommerceKit.TransactionService.xpc/Contents/MacOS/com.apple.CommerceKit.TransactionService
  497 ??         0:00.25 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdflagwriter
  501 ??         0:00.12 /System/Library/CoreServices/EscrowSecurityAlert.app/Contents/MacOS/EscrowSecurityAlert
  502 ??         0:00.05 /System/Library/PrivateFrameworks/BookKit.framework/Versions/A/XPCServices/com.apple.BKAgentService.xpc/Contents/MacOS/com.apple.BKAgentService
  503 ??         0:01.54 /System/Library/CoreServices/ScopedBookmarkAgent
  504 ??         0:03.52 /System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Resources/storedownloadd
  505 ??         0:00.46 /System/Library/PrivateFrameworks/CloudServices.framework/Versions/A/XPCServices/com.apple.sbd.xpc/Contents/MacOS/com.apple.sbd
  515 ??         0:00.24 /System/Library/PrivateFrameworks/CoreSpotlight.framework/Support/com.apple.spotlight.IndexAgent
  522 ??         0:00.35 /System/Library/PrivateFrameworks/WeatherKit.framework/Versions/A/XPCServices/com.apple.WeatherKitService.xpc/Contents/MacOS/com.apple.WeatherKitService
  534 ??         0:03.80 /System/Library/PrivateFrameworks/SafariSafeBrowsing.framework/com.apple.Safari.SafeBrowsing.Service
  535 ??         0:08.90 /System/Library/PrivateFrameworks/CloudDocsDaemon.framework/XPCServices/ContainerMetadataExtractor.xpc/Contents/MacOS/ContainerMetadataExtractor
  536 ??         0:00.35 /System/Library/PrivateFrameworks/CloudServices.framework/Versions/A/Frameworks/EscrowService.framework/Versions/A/XPCServices/com.apple.lakitu.xpc/Contents/MacOS/com.apple.lakitu
  537 ??         0:00.03 /System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/XPCServices/com.apple.CommerceKit.TransactionService.xpc/Contents/MacOS/com.apple.CommerceKit.TransactionService
  538 ??         0:01.79 /usr/libexec/SafariCloudHistoryPushAgent
  543 ??         0:06.12 /System/Library/Frameworks/ApplicationServices.framework/Frameworks/ATS.framework/Support/fontd
  547 ??         0:00.07 /System/Library/CoreServices/pbs
  548 ??         0:18.80 /System/Library/Services/AppleSpell.service/Contents/MacOS/AppleSpell -psn_0_213044
  550 ??         0:00.09 /System/Library/Frameworks/InputMethodKit.framework/Versions/A/XPCServices/com.apple.InputMethodKit.TextReplacementService.xpc/Contents/MacOS/com.apple.InputMethodKit.TextReplacementService
  551 ??         0:00.17 /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/XPCServices/DataDetectorsDynamicData.xpc/Contents/MacOS/DataDetectorsDynamicData
  552 ??         0:02.63 /System/Library/PrivateFrameworks/CoreRecents.framework/Versions/A/Support/recentsd
  556 ??         0:00.02 /System/Library/PrivateFrameworks/CharacterPicker.framework/Versions/A/XPCServices/com.apple.CharacterPicker.FileService.xpc/Contents/MacOS/com.apple.CharacterPicker.FileService
  557 ??         0:00.15 /System/Library/PrivateFrameworks/AssetCacheServices.framework/XPCServices/AssetCacheLocatorService.xpc/Contents/MacOS/AssetCacheLocatorService -a
  558 ??         0:00.72 /Library/Application Support/EyeTV/EyeTV Helper.app/Contents/MacOS/EyeTV Helper
  559 ??         0:00.12 /System/Library/CoreServices/FolderActionsDispatcher.app/Contents/MacOS/FolderActionsDispatcher
  560 ??         0:00.02 /usr/libexec/spindump_agent
  562 ??         0:00.07 /System/Library/CoreServices/SocialPushAgent.app/Contents/MacOS/SocialPushAgent
  564 ??         0:00.14 /System/Library/CoreServices/Keychain Circle Notification.app/Contents/MacOS/Keychain Circle Notification
  566 ??         0:01.86 /System/Library/CoreServices/NotificationCenter.app/Contents/MacOS/NotificationCenter
  568 ??         0:00.15 /System/Library/Image Capture/Support/icdd
  569 ??         0:00.25 /System/Library/CoreServices/AppleIDAuthAgent
  573 ??         0:00.03 /System/Library/PrivateFrameworks/AskPermission.framework/Versions/A/Resources/askpermissiond
  575 ??         0:00.17 /System/Library/CoreServices/AirPlayUIAgent.app/Contents/MacOS/AirPlayUIAgent --launchd
  578 ??         0:00.49 /System/Library/CoreServices/WiFiAgent.app/Contents/MacOS/WiFiAgent
  579 ??         0:00.27 /System/Library/CoreServices/diagnostics_agent
  583 ??         0:00.05 /Applications/iTunes.app/Contents/MacOS/iTunesHelper.app/Contents/MacOS/iTunesHelper
  584 ??         0:01.02 /System/Library/PrivateFrameworks/GameCenterFoundation.framework/Versions/A/gamed
  585 ??         0:03.81 /System/Library/CoreServices/cloudphotosd.app/Contents/MacOS/cloudphotosd
  586 ??         0:00.05 /System/Library/PrivateFrameworks/CallHistory.framework/Support/CallHistorySyncHelper
  588 ??         0:00.03 /System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Resources/maspushagent
  589 ??         0:00.14 /System/Library/PrivateFrameworks/CloudPhotoServices.framework/Versions/A/Frameworks/CloudPhotosConfigurationXPC.framework/Versions/A/XPCServices/com.apple.CloudPhotosConfiguration.xpc/Contents/MacOS/com.apple.CloudPhotosConfiguration
  592 ??         0:00.06 /System/Library/CoreServices/NotificationCenter.app/Contents/XPCServices/com.apple.notificationcenterui.WeatherSummary.xpc/Contents/MacOS/com.apple.notificationcenterui.WeatherSummary
  599 ??         0:12.36 /System/Library/PrivateFrameworks/PhotoLibraryPrivate.framework/Versions/A/Support/photolibraryd
  600 ??         0:00.08 /System/Library/PrivateFrameworks/CoreSuggestions.framework/Versions/A/Support/reversetemplated
  601 ??         0:02.21 /System/Library/CoreServices/cloudphotosd.app/Contents/XPCServices/com.apple.ICPPhotoStreamLibraryService.xpc/Contents/MacOS/com.apple.ICPPhotoStreamLibraryService
  605 ??         0:00.03 /usr/sbin/spindump
  606 ??         0:00.02 /System/Library/CoreServices/SubmitDiagInfo server-init
  608 ??         0:01.66 /System/Library/PrivateFrameworks/PhotoLibraryPrivate.framework/Versions/A/Frameworks/PhotoLibraryServices.framework/Versions/A/XPCServices/com.apple.photomoments.xpc/Contents/MacOS/com.apple.photomoments
  609 ??         0:00.03 /System/Library/PrivateFrameworks/PhotoLibrary.framework/Versions/A/XPCServices/com.apple.PhotoIngestService.xpc/Contents/MacOS/com.apple.PhotoIngestService
  610 ??         0:00.01 /System/Library/Frameworks/CoreMediaIO.framework/Versions/A/XPCServices/com.apple.cmio.registerassistantservice.xpc/Contents/MacOS/com.apple.cmio.registerassistantservice
  613 ??         0:00.02 /System/Library/Frameworks/ApplicationServices.framework/Frameworks/PrintCore.framework/Versions/A/printtool agent
  617 ??         0:00.04 /System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Resources/storelegacy
  618 ??         0:00.02 /System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Resources/storeinstalld
  619 ??         0:00.22 /System/Library/PrivateFrameworks/CommerceKit.framework/Resources/LaterAgent.app/Contents/MacOS/LaterAgent
  622 ??         0:00.04 /System/Library/Frameworks/AddressBook.framework/Versions/A/XPCServices/com.apple.AddressBook.InternetAccountsBridge.xpc/Contents/MacOS/com.apple.AddressBook.InternetAccountsBridge
  624 ??         0:00.37 /System/Library/LoginPlugins/BezelServices.loginPlugin/Contents/Resources/BezelUI/BezelUIServer
  639 ??         0:00.04 /System/Library/PrivateFrameworks/CoreCDP.framework/Versions/A/Resources/cdpd
  640 ??         0:00.01 /System/Library/PrivateFrameworks/CoreFollowUp.framework/Versions/A/Support/followupd
  657 ??         0:00.38 /System/Library/PrivateFrameworks/PhotoLibraryPrivate.framework/Versions/A/Frameworks/PhotoLibraryServices.framework/Versions/A/XPCServices/com.apple.photomodel.xpc/Contents/MacOS/com.apple.photomodel
  668 ??         0:00.03 /usr/sbin/distnoted agent
  735 ??         0:00.01 /System/Library/PrivateFrameworks/ToneLibrary.framework/Versions/A/XPCServices/com.apple.tonelibraryd.xpc/Contents/MacOS/com.apple.tonelibraryd
  756 ??         0:00.10 /System/Library/CoreServices/ShareBear.app/Contents/MacOS/ShareBear
  784 ??         0:00.01 /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/XPCServices/com.apple.hiservices-xpcservice.xpc/Contents/MacOS/com.apple.hiservices-xpcservice
  849 ??         0:00.24 /System/Library/PrivateFrameworks/AOSKit.framework/Versions/A/XPCServices/com.apple.iCloudHelper.xpc/Contents/MacOS/com.apple.iCloudHelper
  852 ??         0:00.41 /usr/sbin/ocspd
  865 ??         0:00.07 /usr/libexec/swcd
  876 ??         0:00.32 /System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/XPCServices/ViewBridgeAuxiliary.xpc/Contents/MacOS/ViewBridgeAuxiliary
  882 ??         0:00.03 /System/Library/PrivateFrameworks/SystemAdministration.framework/XPCServices/writeconfig.xpc/Contents/MacOS/writeconfig
  921 ??         0:00.09 /System/Library/CoreServices/CoreServicesUIAgent.app/Contents/MacOS/CoreServicesUIAgent
  922 ??         0:00.01 /System/Library/PrivateFrameworks/HelpData.framework/Versions/A/Resources/helpd
  988 ??         0:00.38 /Applications/Utilities/System Information.app/Contents/MacOS/System Information
  994 ??         0:00.09 /System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Resources/storeuid.app/Contents/MacOS/storeuid
  996 ??         0:00.01 /System/Library/PrivateFrameworks/StoreXPCServices.framework/Versions/A/XPCServices/com.apple.appstore.PluginXPCService.xpc/Contents/MacOS/com.apple.appstore.PluginXPCService
 1002 ??         0:00.03 /System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/XPCServices/com.apple.CommerceKit.TransactionService.xpc/Contents/MacOS/com.apple.CommerceKit.TransactionService
 1007 ??         0:00.07 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker-sizing -c MDSSizingWorker -m com.apple.mdworker.sizing
 1012 ??         0:08.22 /System/Library/CoreServices/backupd.bundle/Contents/Resources/backupd
 1029 ??         0:00.10 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared
 1030 ??         0:00.07 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared
 1034 ??         0:00.12 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared
 1035 ??         0:00.04 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared
 1042 ??         0:00.08 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker-mail -c MDSImporterWorker -m com.apple.mdworker.mail
  506 ttys000    0:00.03 login -pfl frederikriedel /bin/bash -c exec -la bash /bin/bash
  507 ttys000    0:00.02 -bash
  514 ttys001    0:00.02 login -pfl frederikriedel /bin/bash -c exec -la bash /bin/bash
  516 ttys001    0:00.02 -bash
 1043 ttys001    0:00.00 ps -ax
```

**Comment by devinhalladay** [comment] 2016-08-22 19:14
Wow, so weird. I really expected there to be something running under a random name but I don't see anything. Would you be willing to try deleting both Spotio and your local Spotify.app, redownloading Spotio, and then trying? That'd be super helpful in this if you're willing

**Comment by frogg** [comment] 2016-08-22 19:16
Yes that worked :)

**Comment by devinhalladay** [comment] 2016-08-22 19:17
Awesome! If you'd like you can probably redownload the normal Spotify app now so you can have both, just be sure you keep them in different locations and quit one before you start the other!

**Comment by devinhalladay** [comment] 2016-08-22 19:18
Not sure about the root cause so I'll keep looking into it but I'm going to close this issue for now! Thanks for your help!!

**Closed by devinhalladay** 2016-08-22 19:18 UTC
